POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OWZmNzQwNTg3NmRhZTlmOTUzNmQ2OSIsImlhdCI6MTcyMTkxMDMyN30.nG-Ubf6VFfsIu_JwQ-kgXNg0Y6pghvEkcGdx0CU7Q9s
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "example.com",
    "likes": 5,
    "userId": "669ff7405876dae9f9536d69"
}

